package com.netcatty.mobile.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme — Netcatty orange/amber inspired
val md_theme_light_primary = Color(0xFFB74900)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDBC8)
val md_theme_light_onPrimaryContainer = Color(0xFF3B1300)
val md_theme_light_secondary = Color(0xFF735844)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFDBC8)
val md_theme_light_onSecondaryContainer = Color(0xFF2A1708)
val md_theme_light_tertiary = Color(0xFF58633A)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFDCE8B4)
val md_theme_light_onTertiaryContainer = Color(0xFF161E00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFF857468)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF201A17)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF201A17)
val md_theme_light_surfaceVariant = Color(0xFFF3DDD2)
val md_theme_light_onSurfaceVariant = Color(0xFF52443B)

// Dark theme
val md_theme_dark_primary = Color(0xFFFFB68C)
val md_theme_dark_onPrimary = Color(0xFF5E2200)
val md_theme_dark_primaryContainer = Color(0xFF853300)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDBC8)
val md_theme_dark_secondary = Color(0xFFE1C0A5)
val md_theme_dark_onSecondary = Color(0xFF412C1A)
val md_theme_dark_secondaryContainer = Color(0xFF59422F)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFDBC8)
val md_theme_dark_tertiary = Color(0xFFC0CC9A)
val md_theme_dark_onTertiary = Color(0xFF2C350F)
val md_theme_dark_tertiaryContainer = Color(0xFF424C24)
val md_theme_dark_onTertiaryContainer = Color(0xFFDCE8B4)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF9D8D82)
val md_theme_dark_background = Color(0xFF181210)
val md_theme_dark_onBackground = Color(0xFFEDE0DA)
val md_theme_dark_surface = Color(0xFF181210)
val md_theme_dark_onSurface = Color(0xFFEDE0DA)
val md_theme_dark_surfaceVariant = Color(0xFF52443B)
val md_theme_dark_onSurfaceVariant = Color(0xFFD7C3B7)
